// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $('#migrateElectionFromDir').submit(function(e) {
      alert("Coffee's ready!");
      return e.preventDefault();
    });
  });

}).call(this);

//# sourceMappingURL=utils.map
