// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    return $('#migrateEFD').click(function(e) {
      $.ajax({
        url: '/Migration/DirToElection',
        type: 'POST',
        data: {
          dirPath: "foo",
          electionName: "eName",
          eventDate: "eDate"
        },
        success: function(data) {
          return alert(data);
        }
      });
      return e.preventDefault();
    });
  });

}).call(this);

//# sourceMappingURL=utils.map
